# Generated by Django 5.2.17 on 2026-09-23 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('code', models.CharField(help_text='Short code for API references', max_length=50, unique=True)),
                ('domain', models.CharField(blank=True, help_text='Primary domain (e.g., company.com)', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['code'], name='licensing_c_code_6c97af_idx'), models.Index(fields=['is_active'], name='licensing_c_is_acti_99ad96_idx')],
            },
        ),
        migrations.CreateModel(
            name='SystemLicense',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(choices=[('dms', 'Document Management System'), ('inventory', 'Inventory Management'), ('financial', 'Financial System')], max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('licensed_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Null means perpetual', null=True)),
                ('license_key', models.CharField(blank=True, help_text='External license key if applicable', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenses', to='licensing.clientorganization')),
            ],
            options={
                'ordering': ['organization', 'system'],
                'indexes': [models.Index(fields=['organization', 'system'], name='licensing_s_organiz_b570be_idx'), models.Index(fields=['is_active'], name='licensing_s_is_acti_d60234_idx')],
                'unique_together': {('organization', 'system')},
            },
        ),
        migrations.CreateModel(
            name='UserSystemRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('system', models.CharField(choices=[('dms', 'Document Management System'), ('inventory', 'Inventory Management'), ('financial', 'Financial System')], max_length=50)),
                ('role', models.CharField(choices=[('dms_admin', 'DMS Administrator'), ('dms_editor', 'DMS Editor'), ('dms_viewer', 'DMS Viewer'), ('inventory_admin', 'Inventory Administrator'), ('inventory_user', 'Inventory User'), ('financial_admin', 'Financial Administrator'), ('financial_user', 'Financial User')], max_length=50)),
                ('provisioned_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_system_roles', to='licensing.clientorganization')),
                ('provisioned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provisioned_roles', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='system_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user', 'system'],
                'indexes': [models.Index(fields=['user', 'system'], name='licensing_u_user_id_336062_idx'), models.Index(fields=['organization', 'system'], name='licensing_u_organiz_b202e9_idx'), models.Index(fields=['is_active'], name='licensing_u_is_acti_856fb9_idx')],
                'unique_together': {('user', 'organization', 'system')},
            },
        ),
    ]
