# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("licensing", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="UserSystemRole",
        ),
        migrations.AlterField(
            model_name="systemlicense",
            name="system",
            field=models.CharField(
                choices=[
                    ("dms", "Document Management"),
                    ("inventory", "Inventory Management"),
                ],
                max_length=50,
            ),
        ),
    ]
