# Generated by Django 5.2.17 on 2026-09-23 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event', models.CharField(choices=[('user.login', 'User Login'), ('user.login_failed', 'Login Failed'), ('user.break_glass_login', 'Break-Glass Login (Emergency Native Auth)'), ('user.break_glass_login_failed', 'Break-Glass Login Failed'), ('user.mfa_enabled', 'MFA Enabled'), ('user.mfa_disabled', 'MFA Disabled'), ('user.password_changed', 'Password Changed'), ('user.password_reset', 'Password Reset'), ('user.created', 'User Created'), ('user.updated', 'User Updated'), ('user.deleted', 'User Deleted'), ('user.activated', 'User Activated'), ('user.deactivated', 'User Deactivated'), ('organization.created', 'Organization Created'), ('organization.updated', 'Organization Updated'), ('organization.deleted', 'Organization Deleted'), ('license.granted', 'System License Granted'), ('license.revoked', 'System License Revoked'), ('license.expired', 'System License Expired'), ('system_role.granted', 'System Role Granted'), ('system_role.revoked', 'System Role Revoked'), ('system_role.updated', 'System Role Updated'), ('system_access.granted', 'System Access Granted (SSO Redirect)'), ('system_access.denied', 'System Access Denied (Not Provisioned)'), ('system_access.blocked', 'System Access Blocked (Not Licensed)')], db_index=True, max_length=60)),
                ('object_type', models.CharField(blank=True, max_length=60)),
                ('object_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('object_repr', models.CharField(blank=True, max_length=255)),
                ('changes', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
            },
        ),
    ]
